<?php exit;?>04-27 16:19:43 | 2 | file_put_contents(D:\phpStudy\WWW\zyznhh\caches\advertisement_js/1.js): failed to open stream: No such file or directory | phpcms\modules\advertisement\classes\html.class.php | 67
<?php exit;?>04-27 16:19:43 | 2 | chmod(): No such file or directory | phpcms\modules\advertisement\classes\html.class.php | 68
<?php exit;?>04-27 16:21:18 | 2 | extract() expects parameter 1 to be array, string given | phpcms\modules\advertisement\space.php | 165
<?php exit;?>04-28 09:21:31 | 2 | fsockopen(): php_network_getaddresses: getaddrinfo failed: ��֪������������  | phpcms\libs\classes\http.class.php | 84
<?php exit;?>04-28 09:21:31 | 2 | fsockopen(): unable to connect to juhe.phpcms.cn:80 (php_network_getaddresses: getaddrinfo failed: ��֪������������ ) | phpcms\libs\classes\http.class.php | 84
<?php exit;?>04-28 09:24:08 | 2 | Invalid argument supplied for foreach() | phpcms\modules\admin\classes\module_api.class.php | 55
<?php exit;?>04-28 09:25:24 | 2 | fsockopen(): php_network_getaddresses: getaddrinfo failed: ��֪������������  | phpcms\libs\classes\http.class.php | 84
<?php exit;?>04-28 09:25:24 | 2 | fsockopen(): unable to connect to juhe.phpcms.cn:80 (php_network_getaddresses: getaddrinfo failed: ��֪������������ ) | phpcms\libs\classes\http.class.php | 84
<?php exit;?>04-28 09:37:38 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:37:38 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:00 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:00 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:07 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:07 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:20 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:20 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:28 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:28 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:28 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:28 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:29 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:47:29 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:48:17 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:48:17 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:48:30 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:48:30 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:48:39 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:48:39 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:49:49 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 57
<?php exit;?>04-28 09:49:49 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 57
<?php exit;?>04-28 09:50:06 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:50:06 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banner.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:01 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:01 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:06 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:06 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:30 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:30 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:36 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:36 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:48 | 2 | include(D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php): failed to open stream: No such file or directory | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 09:52:48 | 2 | include(): Failed opening 'D:\phpStudy\WWW\zyznhh\phpcms\modules\banner\templates\banners.tpl.php' for inclusion (include_path='.;C:\php\pear') | phpcms\modules\banner\banner.php | 56
<?php exit;?>04-28 11:08:00 | 2 | Missing argument 1 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>04-28 11:08:00 | 2 | Missing argument 2 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>04-28 11:08:00 | 2 | Missing argument 3 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>04-28 11:08:00 | 2 | Missing argument 4 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>04-28 11:08:03 | 2 | Missing argument 1 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>04-28 11:08:03 | 2 | Missing argument 2 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>04-28 11:08:03 | 2 | Missing argument 3 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>04-28 11:08:03 | 2 | Missing argument 4 for zymemberApi::account_login(), called in D:\phpStudy\WWW\zyznhh\phpcms\libs\classes\application.class.php on line 31 and defined | phpcms\modules\zymember\zymemberApi.php | 236
<?php exit;?>05-05 10:41:48 | 2 | rmdir(D:/phpStudy/WWW/zyznhh/phpcms/languages/zh-cn/test_create_dir/): No such file or directory | phpcms\libs\functions\dir.func.php | 154
<?php exit;?>05-05 10:41:48 | 2 | mkdir(): File exists           | phpcms\libs\functions\dir.func.php | 30
<?php exit;?>05-05 10:41:48 | 2 | rmdir(D:/phpStudy/WWW/zyznhh/phpcms/languages/zh-cn/test_create_dir/): No such file or directory | phpcms\libs\functions\dir.func.php | 154
<?php exit;?>05-05 10:41:48 | 2 | Invalid argument supplied for foreach() | phpcms\modules\admin\classes\module_api.class.php | 55
<?php exit;?>05-05 10:43:30 | 2 | fsockopen(): php_network_getaddresses: getaddrinfo failed: ��֪������������  | phpcms\libs\classes\http.class.php | 84
<?php exit;?>05-05 10:43:30 | 2 | fsockopen(): unable to connect to juhe.phpcms.cn:80 (php_network_getaddresses: getaddrinfo failed: ��֪������������ ) | phpcms\libs\classes\http.class.php | 84
